### ISSUE TITLE
TelegramBot not detected

### ISSUE THREAD

**Issue by jespertheend** [JefferyHus/es6-crawler-detect#10]
```js
const {Crawler} = require("es6-crawler-detect/src");
let crawlDetector = new Crawler();
crawlDetector.isCrawler("TelegramBot (like TwitterBot)"); //false
```

Strangely enough it does get detected on https://crawlerdetect.io/?q=TelegramBot%20(like%20TwitterBot)

I'm using version 3.0.0 on macOS

**Comment by JefferyHus** [comment]
Thanks for opening the issue, I will check it.

**Comment by JefferyHus** [comment]
I have just tested and it is working for me. Which version are you using?

**Comment by JefferyHus** [comment]
@jespertheend I have added a test case [here](https://github.com/JefferyHus/es6-crawler-detect/blob/93db2ccc3cab880810079054b6ddbd7578474b4f/test/lib/crawler.test.js#L13)

For you only, please check it.

**Comment by jespertheend** [comment]
Ah hahah thank you :)
I'm not sure why it isn't working for me then. My `package.json` says `"es6-crawler-detect": "^3.0.0"`. I'll double check.

**Comment by jespertheend** [comment]
Hmm, ok I'm not sure what exactly the difference is between this repo and what is currently published on npm. But when I do `npm i https://github.com/JefferyHus/es6-crawler-detect.git` instead of `npm i es6-crawler-detect` it does detect Telegram properly.
So I'm guessing this will be fixed the next time this package gets updated.

**Comment by JefferyHus** [comment]
Yes I will be pushing a patch soon, thanks again for the issue mate :)

**Comment by JefferyHus** [comment]
@jespertheend I have published the latest updates, please check npm now 👍

**Comment by jespertheend** [comment]
I'm probably a bit late with this but I just checked and it seems to be working. Thanks for the quick fix!

**Comment by JefferyHus** [comment]
Sure thing :)
