### ISSUE TITLE
Library cannot be imported in Node.js

### ISSUE THREAD

**Issue by liangyuanruo** [JefferyHus/es6-crawler-detect#14]
**Describe the bug**
`package.json` has a `main` property referring to `index.js`, but there is no such file. This should be pointing to `src/index.js` or `dist/main.bundle.js`

**To Reproduce**
1. `npm install es6-crawler-detect`
2. Enter `node` interpreter
3. `require('es6-crawler-detect')`

**Expected behavior**
Library should be loaded in NodeJS.

**Comment by JefferyHus** [comment]
Fixed in this commit 5386e65f97eaaa3a123ad276f119ff906cfbe090
