### ISSUE TITLE
Support for Typescript file ?

### ISSUE THREAD

**Issue by duongleh** [JefferyHus/es6-crawler-detect#15]

**Comment by JefferyHus** [comment]
I have never thought of this before. But I guess if there is enough time and help, we can release a TS version

**Comment by Abhirup-99** [comment]
Are you working on this? May I take a try at this one?

**Comment by duongleh** [comment]
> Are you working on this? May I take a try at this one?

go for it !

**Comment by JefferyHus** [comment]
> Are you working on this? May I take a try at this one?

Yes you can go for it

**Comment by Abhirup-99** [comment]
There is a cyclone and internet disruption in my area. It may take some time for me to get back to you on this.

**Comment by persunde** [comment]
Please add TS support. That would be appreciated :)

**Comment by JefferyHus** [comment]
@persunde I will get the TS support done asap :)
