### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined at Crawler.isCrawler

### ISSUE THREAD

**Issue by IgorKurkov** [JefferyHus/es6-crawler-detect#19]
**Describe the bug**
Not work as should with express.

**To Reproduce**
1. Installed
2. Set in express by instructions
3. started server
4. saw the error

**Expected behavior**
there no idea why it does not see user-agent from request.

**Desktop (please complete the following information):**
 - OS: windows 10 pro x64
 - Browser chrome latest (83)

Just FYI. I think its some very tiny bug, but it does not work as should. Check it please

**Comment by JefferyHus** [comment]
You were right, yeah I fixed the issue and will open a PR soon and hopefully by tomorrow morning you can pull the new updates and that's it

**Comment by JefferyHus** [comment]
@IgorKurkov This is the fix #20
