### ISSUE TITLE
crawlers not detected when use auto-detect headers in node

### ISSUE THREAD

**Issue by vatanuki** [JefferyHus/es6-crawler-detect#34]
**Steps to reproduce the behavior:**
1. use example ECMAScript 6 (ES6)
2. code to check: "check the current visitor's useragent" (CrawlerDetector.isCrawler())
3. remove code: "check a user agent string"
4. request example using curl
5. it will return **{}**

**Expected behavior**
should return **curl**

**it will work if**
in file crawler.js on line 75 update **header** to **header.toLowerCase()** like this:
`userAgent += this.httpHeaders[header.toLowerCase()] + ' ';`

am i using the library in the wrong way? or this is a bug?

**Comment by JefferyHus** [comment]
Please provide me with more details:
- Node version?
- Print the Http Headers array & share it in a comment
- Mention any frameworks you are using
- Minor example to reproduce

**Comment by JefferyHus** [comment]
@vatanuki can you please update the issue, otherwise it will be closed

**Comment by vatanuki** [comment]
@JefferyHus sure

node -v
**v14.18.2**

test code:
```javascript
'use strict';

const express = require('express')
const { Crawler } = require('es6-crawler-detect')
const app = express()

app.get('/curl', function async (request, response) {
  var CrawlerDetector = new Crawler(request)
  response.send( CrawlerDetector.isCrawler() ? 'detected' : 'not detected')
})

app.listen(3000)
```

curl test request:
```
curl -v http://127.0.0.1:3000/curl
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /curl HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 12
< ETag: W/"c-O+YmnRNLEJrWQnm49UdT/kB8u0I"
< Date: Sat, 25 Dec 2021 03:11:24 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host 127.0.0.1 left intact
not detected
```

posible fix:
```diff
diff --git a/src/lib/crawler.js b/src/lib/crawler.js
index 047f2c7..43e2314 100644
--- a/src/lib/crawler.js
+++ b/src/lib/crawler.js
@@ -76,7 +76,7 @@ class Crawler {
     ) {
       for (const header of this.getUaHttpHeaders()) {
         if (Object.keys(this.httpHeaders).indexOf(header.toLowerCase()) >= 0) {
-          userAgent += this.httpHeaders[header] + ' ';
+          userAgent += this.httpHeaders[header.toLowerCase()] + ' ';
         }
       }
     }
```

curl test request after fix:
```
curl -v http://127.0.0.1:3000/curl
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET /curl HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: text/html; charset=utf-8
< Content-Length: 8
< ETag: W/"8-vL//2K5LHFy1YRyMCLFAJ5fXQXc"
< Date: Sat, 25 Dec 2021 03:14:34 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host 127.0.0.1 left intact
detected
```

**Comment by JefferyHus** [comment]
@vatanuki can you test this branch and see if it works for you? https://github.com/JefferyHus/es6-crawler-detect/pull/41
In the meantime I will try to add more test cases which includes your case here and see if the changes you are introducing are not going to break the module

**Comment by vatanuki** [comment]
@JefferyHus tested (branch feat/testing-cases), its still not detected

**Comment by JefferyHus** [comment]
@vatanuki #41 is now fixing your bug, thanks for flagging this bug. You can also check the test cases that performs some simulations on the headers & request object
