### ISSUE TITLE
isCrawler() doesnt detect Crawler

### ISSUE THREAD

**Issue by ngmiduc** [JefferyHus/es6-crawler-detect#36]
**Describe the bug**
I use this lib on Google Cloud Functions and somehow it doesn't detect any crawlers when I execute `isCrawler()`.
I am not sure if I am doing something wrong but I followed the code in the docs.

At the end I used this: 

```
if (CrawlerDetector.isCrawler(req.get("User-Agent"))) {
        console.log("Crawler detected!")
}
```

But without specifying the string, it didn't work.

**Comment by JefferyHus** [comment]
Can you share the `User Agent` that the module is failing to detected?

**Comment by ngmiduc** [comment]
I used the Google bot from Chrome Dev Tools. 
When I pasted the user agent string directly into the function, it worked. But without specifying the string, it didnt.

**Comment by JefferyHus** [comment]
This could be a problem with your framework or Node.js have deprecated something in a newer version, with that said please share more details.
- Node version?
- Frameworks
- Print the Http headers array and share it in a comment

**Comment by ngmiduc** [comment]
I am using Google Cloud Functions with Node version 14.
When it get's executed by the browser I get this header on request on the server::

```
>  {
>    'x-forwarded-host': 'localhost:5000',
>    'x-original-url': '/d/sdeqwd',
>    pragma: 'no-cache',
>    'cache-control': 'no-cache',
>    cookie: 'ajs_anonymous_id=...."',
>    connection: 'keep-alive',
>    'upgrade-insecure-requests': '1',
>    'user-agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
>    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
>    'sec-fetch-site': 'none',
>    'sec-fetch-mode': 'navigate',
>    'sec-fetch-user': '?1',
>    'sec-fetch-dest': 'document',
>    'accept-encoding': 'gzip, deflate, br',
>    'accept-language': 'en-US,en;q=0.9,fr;q=0.8,en-GB;q=0.7,nl;q=0.6,de;q=0.5',
>    'x-client-version': 'FirebaseCLI/undefined',
>    host: 'localhost:5001'
>  }
```

**Comment by gptt916** [comment]
Looks like googlebot isn't in the list of accepted crawlers? I opened a PR heere: https://github.com/JefferyHus/es6-crawler-detect/pull/37

**Comment by ngmiduc** [comment]
The thing is, when I pass the string directly into the function call. It works !

**Comment by JefferyHus** [comment]
@gptt916 google bot is already there. The issue could be something else than the regex. As long as passing the string manually works then probably the http headers are not parsed correctly or the headers are not present in runtime.

**Comment by JefferyHus** [comment]
This is related https://github.com/JefferyHus/es6-crawler-detect/issues/34

**Comment by JefferyHus** [comment]
@ngmiduc can you test again? I have updated the database with more bots including google bots

**Comment by JefferyHus** [comment]
This is fixed by https://github.com/JefferyHus/es6-crawler-detect/pull/41
