### ISSUE TITLE
(Browser runtime) `ReferenceError: Buffer is not defined`

### ISSUE THREAD

**Issue by strarsis** [JefferyHus/es6-crawler-detect#46]
**Describe the bug**
During browser runtime this JavaScript error occurs: `ReferenceError: Buffer is not defined`

**To Reproduce**
1. Import and use `Crawler.isCrawler(...)`.
2. Build with webpack.
3. Run in latest Chrome.
Note that a JavaScript error occurs:
````
ReferenceError: Buffer is not defined
    at e.exports.isCrawler (891.3bf818.js:1:1061)
````

**Expected behavior**
No runtime errors.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 22]: `108.0.5359.94`

**Comment by JefferyHus** [comment]
Thanks for reporting, I will check it out asap

**Comment by Startouf** [comment]
This happens to me when I'm trying to run the crawler at runtime inside my Angular application. This app seems to be made for nodejs only environments (or at least Buffer() isn't something that seems to be available in the context of my angular app)

Since this lib is not written using typescript, so it's hard to check where things go wrong.

**Comment by Startouf** [comment]
Hmm, maybe we need to use something like this https://github.com/feross/buffer
see also the recommended way of using the Buffer for node : https://github.com/nodejs/node/blob/main/doc/api/buffer.md

**Comment by JefferyHus** [comment]
It has been long time I have not checked it un the browser, but the initial example was working fine for me. [Browser example](https://github.com/JefferyHus/es6-crawler-detect/blob/master/example/node/index.html)

**Comment by JefferyHus** [comment]
But I would suggest to use what @Startouf shared about the `buffer` library

**Comment by strarsis** [comment]
@JefferyHus: The browser example directly loads the minified script. But I want to import in JavaScript as an ES module.

**Comment by JefferyHus** [comment]
That would then call for some buffer polyfill, the library mentioned above will do the job.

**Comment by JefferyHus** [comment]
@strarsis any updates on this one?

**Comment by strarsis** [comment]
Well, partially. I have issues with getting the buffer polyfill to work and also keeping the overall size low.

**Comment by JefferyHus** [comment]
Let me know you need more help, I will be forced to close this issue within a week.
