### ISSUE TITLE
Breaks if request does not have user agent

### ISSUE THREAD

**Issue by sharad2802** [JefferyHus/es6-crawler-detect#54]
**Describe the bug**
Code Breaks if request does not have user agent

**To Reproduce**
send empty user agent

/app/joshpwa/node_modules/es6-crawler-detect/src/lib/crawler.js:103
    agent = agent.replace(this.compiledExclusions, '');
                  ^

TypeError: Cannot read property 'replace' of undefined
    at Crawler.isCrawler (/app/joshpwa/node_modules/es6-crawler-detect/src/lib/crawler.js:103:19)

**Comment by JefferyHus** [comment]
@sharad2802 can you please test [this PR](https://github.com/JefferyHus/es6-crawler-detect/pull/60), it might fix your issue.
