### ISSUE TITLE
Incorrect Crawler.getMatches

### ISSUE THREAD

**Issue by FahriDevZ** [JefferyHus/es6-crawler-detect#6]
![Screenshot from 2019-08-22 20 13 44](https://user-images.githubusercontent.com/22916016/63517565-658b6800-c519-11e9-8112-721b0edadc9d.png)

Bot agent is `Facebot`, but the output is `acebot`

I just run code like this in middleware
```
const agent = req.headers['user-agent'];

req.Crawler.isCrawler(agent);
const output = req.Crawler.getMatches();

console.log('userAgent: ', agent);
console.log('getMatches: ', output);
```

Edit:
Im using `es6-crawler-detect@^3.0.0`

**Comment by JefferyHus** [comment]
This must be a regex problem, Can you please hand me with the full `user-agent` string or is it just `Facebot`?

**Comment by FahriDevZ** [comment]
@JefferyHus Yap just `Facebot`, this crawler from Facebook

**Comment by JefferyHus** [comment]
@melbarch can you open a PR?

**Comment by JefferyHus** [comment]
Thanks everyone : )
